description = "Registry for the Planar.jl ecosystem (packages of the BubbleParticles/Planar.jl monorepo)"
name = "PlanarRegistry"
repo = "https://github.com/BubbleParticles/PlanarRegistry.git"
uuid = "55da71c0-fafb-41ae-8249-1bb3b7066f5d"

[packages.01937fd2-c099-442f-ae89-75fa208aad36]
name = "PlanarOptim"
path = "Packages/P/PlanarOptim"

[packages.38b379f7-ca41-4278-b0dc-774ced1e32bb]
name = "PlanarDownloadTool"
path = "Packages/P/PlanarDownloadTool"

[packages.646fb1a4-6797-441d-ad18-3bdbde2eb86b]
name = "Planar"
path = "Packages/P/Planar"

[packages.799974c5-219d-476a-ada7-be492421c276]
name = "PlanarFeatureSelection"
path = "Packages/P/PlanarFeatureSelection"

[packages.bc793e09-ff97-408c-9766-388aa928ad5c]
name = "PlanarStrategyTools"
path = "Packages/P/PlanarStrategyTools"

[packages.d4fe19c2-883d-48d3-92d7-80b36677371b]
name = "PlanarStrategyStats"
path = "Packages/P/PlanarStrategyStats"

[packages.df15b565-ff7f-4c64-9bc8-38e9343ea891]
name = "PlanarDev"
path = "Packages/P/PlanarDev"

[packages.e8cdc95d-7257-4c38-ab0e-cc8a28c19776]
name = "PlanarPython"
path = "Packages/P/PlanarPython"
